pool:
    name: Azure Pipelines
    demands: npm
    vmImage: ubuntu-latest

trigger: none

steps:
    - task: Npm@1
      displayName: "npm ci"
      inputs:
          verbose: false

    - task: Npm@1
      displayName: "npm run build"
      inputs:
          command: custom
          verbose: false
          customCommand: "run build:development"

    - task: Npm@1
      displayName: "npm run test-final"
      inputs:
          command: custom
          verbose: false
          customCommand: "run test-final"

    - task: PublishTestResults@2
      inputs:
          testRunner: JUnit
          testResultsFiles: "**/junit.xml"

    - task: PublishCodeCoverageResults@1
      inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
          reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
