export const chords = {
    "C-dur": ["C", "E", "G"],
    "C#-dur": ["C#", "E#", "G#"],
    "D-dur": ["D", "F#", "A"],
    "D#-dur": ["D#", "G", "A#"],
    "E-dur": ["E", "G#", "B"],
    "F-dur": ["F", "A", "C"],
    "F#-dur": ["F#", "A#", "C#"],
    "G-dur": ["G", "H", "D"],
    "G#-dur": ["G#", "C", "D#"],
    "A-dur": ["A", "C#", "E"],
    "A#-dur": ["A#", "D", "F"],
    "H-dur": ["B", "D#", "F#"],

    "C-moll": ["C", "D#", "G"],
    "C#-moll": ["C#", "E", "G#"],
    "D-moll": ["D", "F", "A"],
    "D#-moll": ["D#", "F#", "A#"],
    "E-moll": ["E", "G", "H"],
    "F-moll": ["F", "G#", "C"],
    "F#-moll": ["F#", "A", "C#"],
    "G-moll": ["G", "A#", "D"],
    "G#-moll": ["G#", "H", "D#"],
    "A-moll": ["A", "C", "E"],
    "A#-moll": ["A#", "C#", "F"],
    "H-moll": ["B", "D", "F#"],
}

